{% set name = "mendeleev" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7d513a3be0c2b45369c3c041eb949a76bc92ee42d833b1dee0048a919d3f9a78

build:
  number: 1
  entry_points:
    - element.py = mendeleev.cli:clielement
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pyfiglet
    - colorama
    - sqlalchemy
    - pandas
    - numpy
    - poetry
    - setuptools
  run:
    - python >={{ python_min }},<3.13
    - pip
    - numpy <2.0,>=1.26
    - pandas >=1.0.0
    - sqlalchemy >=1.4.0
    - pyfiglet >=0.8,<0.9
    - colorama >=0.4.6,<0.5.0
    - pygments >=2.11.2,<3.0
    - deprecated
    - pydantic

test:
  requires:
    - python {{ python_min }}
  imports:
    - mendeleev
  commands:
    - element.py --help
    - pip check

about:
  home: https://github.com/lmmentel/mendeleev
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A perdioc table of elements API and a database of atomic properties.

  description: |
    This package provides an API for accessing various properties 
    of elements from the periodic table of elements.
  doc_url: http://mendeleev.readthedocs.org
  dev_url: https://github.com/lmmentel/mendeleev

extra:
  recipe-maintainers:
    - jan-janssen
    - lmmentel
