{% set name = "mendeleev" %}
{% set version = "0.20.1" %}
{% set python_min = "3.12" %}  # [with_python_gt_312 == True]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26f27099f0587cab82dd7f84ee31a5c48e994eb478ea2a92756c5fd50764f7da

build:
  number: 1
  entry_points:
    - element.py = mendeleev.cli:clielement
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pyfiglet
    - colorama
    - sqlalchemy
    - pandas
    - numpy
    - poetry
    - setuptools
  run:
    - python >={{ python_min }},<3.13
    - pip
    - numpy <3.0,>=2.0  # [with_python_gt_312 == True]
    - numpy >=1.21.0,<2.0.0  # [with_python_gt_312 == False]
    - pandas >=1.0.0
    - sqlalchemy >=1.4.0
    - pyfiglet >=0.8.0.post1,<0.9.0
    - colorama >=0.4.6,<0.5.0
    - pygments >=2.11.2,<3.0.0
    - deprecated >=1.2.14,<2.0.0
    - pydantic >=2.9.2,<3.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - mendeleev
  commands:
    - element.py --help
    - pip check

about:
  home: https://github.com/lmmentel/mendeleev
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A perdioc table of elements API and a database of atomic properties.

  description: |
    This package provides an API for accessing various properties 
    of elements from the periodic table of elements.
  doc_url: http://mendeleev.readthedocs.org
  dev_url: https://github.com/lmmentel/mendeleev

extra:
  recipe-maintainers:
    - jan-janssen
    - lmmentel
