{% set name = "mendeleev" %}
{% set version = "1.2.0" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8be5a6fe9c3780ffb52b179b6e0720eb5aff898e227139845b6a9b81babd67ac

build:
  number: {{ build }}
  string: "pymin{{ python_min|replace('.', '') }}_h{{ PKG_HASH }}_{{ build }}"
  entry_points:
    - element.py = mendeleev.cli:clielement
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pyfiglet
    - colorama
    - sqlalchemy
    - pandas
    - numpy
    - poetry
    - setuptools <80
  run:
    - pint >=0.24.4,<0.25.0
    - pydantic-core >=2.23.0,<3.0.0
    - python >={{ python_min }}
    - pip
    - numpy >=2.0.0,<3.0.0
    - pandas >=2.1.0,<3.0.0
    - sqlalchemy >=1.4.0
    - pyfiglet >=0.8.0.post1,<0.9.0
    - colorama >=0.4.6,<0.5.0
    - pygments >=2.11.2,<3.0.0
    - deprecated >=1.2.14,<2.0.0
    - pydantic >=2.12.0,<3.0.0
    - setuptools <80

test:
  requires:
    - python {{ python_min }}
  imports:
    - mendeleev
  commands:
    - element.py --help
    - pip check

about:
  home: https://github.com/lmmentel/mendeleev
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A perdioc table of elements API and a database of atomic properties.

  description: |
    This package provides an API for accessing various properties 
    of elements from the periodic table of elements.
  doc_url: http://mendeleev.readthedocs.org
  dev_url: https://github.com/lmmentel/mendeleev

extra:
  recipe-maintainers:
    - jan-janssen
    - lmmentel
