schema_version: 1

context:
  name: mendeleev
  version: 1.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 24e7bfd2981aedf5fe1ef7f0e4814d78005c47e57320a92097b3fd89313c21c5

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - element.py = mendeleev.cli:clielement

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - pyfiglet
    - colorama
    - sqlalchemy
    - pandas
    - numpy
    - poetry
    - setuptools <80
  run:
    - pint >=0.24.4,<0.25.0
    - pydantic-core >=2.23.0,<3.0.0
    - python >=${{ python_min }}
    - pip
    - numpy >=2.0.0,<3.0.0
    - pandas >=2.1
    - sqlalchemy >=1.4.0
    - pyfiglet >=0.8.0.post1,<0.9.0
    - colorama >=0.4.6,<0.5.0
    - pygments >=2.11.2,<3.0.0
    - deprecated >=1.2.14,<2.0.0
    - pydantic >=2.12.0,<3.0.0
    - setuptools <80

tests:
  - python:
      imports:
        - mendeleev
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - element.py --help

about:
  license: MIT
  license_file: LICENSE
  summary: A perdioc table of elements API and a database of atomic properties.
  description: |
    This package provides an API for accessing various properties
    of elements from the periodic table of elements.
  homepage: https://github.com/lmmentel/mendeleev
  repository: https://github.com/lmmentel/mendeleev
  documentation: http://mendeleev.readthedocs.org

extra:
  recipe-maintainers:
    - jan-janssen
    - lmmentel
