travis:
  secure:
    BINSTAR_TOKEN: eUkeG02cfYnLWfHWWW6t343tqyCYqTQ/MDhZ7lNenSbjnaAfza8gMfHaSLh3YkRzx7grvOAj+cIZkSaIdzBQ54peVNwoDKwDtqP2PwuVfbvJafzM9DAG892jPWelWK0/yZ3DcW3TQ2EEFAf0UH0M5l8iZ4busZYLG52I5+yA4KJtqi7Fh9x9lDbazgLK3NHxVClFOlF2Go1fnE87SvcLr1H9683z4RPpk+Xf9foo7/FdWS5de8Of+X0kVKnynWZumdB3ea9HlvlOwX4wsAN4Vq6N2TympaUJHTGzJnsu263L1z+hMCf5e8nOBLoAKbLoUgfAdI3CYaGd04h8grqup+301D/7hm2TyjlkksinCnqx97j9vs9gEPGut4YeWJ8wg8ntilDuD4vU3baEsO3I+n/wbrbbUxK2UJWH+lzu0JCIxcK7wALDcYC2l0VEovrY/spb+468xTAL1cBXXAV65YELGnGHz65gnVS5zVNx5FK76x627EAFNH/TEWlaXMjkoJ1XD2dk1LHiTCp5BxuCTv9Xb2wm+DLkQAvaFXR8HjKa++CKpZ1wQsCryvhkgH4602qMeIM76QGF7hrxjEJ2LBlVvzhJSDYdZ5GtSZy6v6kSNev12vD/LNkHK5FYt+OtwdEjkoVAc69eOpotPiVpDWRA7tmWF0dJqhqoYQUL6lM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
